# Generated by Django 4.1.9 on 2023-05-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embedded',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='embedded',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
