# Generated by Django 4.1.9 on 2023-05-10 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_embedded_options_embedded_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embedded',
            options={},
        ),
        migrations.RemoveField(
            model_name='embedded',
            name='updated',
        ),
    ]
