# Generated by Django 4.1.9 on 2023-05-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_embedded_options_remove_embedded_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_Img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
